apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "halo.fullname" . }}-mysql
  labels:
    {{- include "halo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "halo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "halo.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: mysql-storage
          hostPath:
            path: {{ .Values.mysql.volume.hostPath }}
            type: DirectoryOrCreate
        - name: mysql-backup-storage
          hostPath:
            path: {{ .Values.mysql.volume.backup }}
            type: DirectoryOrCreate
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          args:
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_general_ci'
            - '--explicit_defaults_for_timestamp=true'
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.config.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.config.database }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-backup-storage
              mountPath: /data/mysqlBackup
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}