apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo.fullname" . }}-mysql
  labels:
    {{- include "halo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "halo.selectorLabels" . | nindent 4 }}