nameOverride: ""
fullnameOverride: ""

halo:
  image:
    repository: halohub/halo
    pullPolicy: IfNotPresent
    tag: ""
  config:
    adminUsername: root
    adminPassword: root
    externalUrl: https://chart-example.local/
  volume:
    path: /var/lib/halo2
  resources: {}
  tolerations: []
  affinity: {}

mysql:
  image:
    repository: mysql
    tag: "8.0.31"
    pullPolicy: IfNotPresent
  config:
    rootPassword: root-password
    database: halo
  volume:
    hostPath: /var/lib/mysql
    backup: /var/lib/mysql-backup
  resources: {}
  tolerations: []
  affinity: {}

nodeSelector:
  {}
  # kubernetes.io/hostname: xxx

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
    # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
