apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatgpt-web-share.fullname" . }}-chatgpt-share
  labels:
    {{- include "chatgpt-web-share.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "chatgpt-web-share.selectorLabels" . | nindent 4 }}
