apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatgpt-web-share.fullname" . }}-chatgpt-proxy-server
  labels:
    {{- include "chatgpt-web-share.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chatgpt-web-share.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatgpt-web-share.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-chatgpt-proxy-server
          image: "linweiyuan/chatgpt-proxy-server"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9515
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9515
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3            
          readinessProbe:
            tcpSocket:
              port: 9515
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9515
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
