apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatgpt-web-share.fullname" . }}-chatgpt-share
  labels:
    {{- include "chatgpt-web-share.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chatgpt-web-share.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatgpt-web-share.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: chatgpt-storage
          hostPath:
            path: {{ .Values.volume.path }}
            type: DirectoryOrCreate
        - name: chatgpt-config
          configMap:
            name: {{ include "chatgpt-web-share.fullname" . }}-configuration
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/moeakwak/chatgpt-web-share:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CHATGPT_BASE_URL
              value: http://{{ include "chatgpt-web-share.fullname" . }}-go-chatgpt-api:8080/chatgpt/
          volumeMounts:
            - name: chatgpt-storage
              mountPath: /data
            - name: chatgpt-config
              mountPath: /app/backend/api/config/config.yaml
              subPath: config
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3            
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
