apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatgpt-web-share.fullname" . }}-go-chatgpt-api
  labels:
    {{- include "chatgpt-web-share.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "chatgpt-web-share.selectorLabels" . | nindent 4 }}
