apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatgpt-web-share.fullname" . }}-go-chatgpt-api
  labels:
    {{- include "chatgpt-web-share.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chatgpt-web-share.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatgpt-web-share.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-go-chatgpt-api
          image: "linweiyuan/go-chatgpt-api"
          imagePullPolicy: IfNotPresent
          env:
            - name: GIN_MODE
              value: release
            - name: CHATGPT_PROXY_SERVER
              value: http://{{ include "chatgpt-web-share.fullname" . }}-chatgpt-proxy-server:9515
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3            
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
