env:
  []
  # - name: OPENAI_API_KEY
  #   value: 'xxx'
  # - name: BASE_URL
  #   value: 'https://api.openai-sb.com'
  # - name: CODE
  #   value: 'xxx'
  # - name: HIDE_USER_API_KEY
  #   value: '0'
  # - name: DISABLE_GPT4
  #   value: '1'

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
    # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector:
  {}
  # kubernetes.io/hostname: xxx

image:
  repository: yidadaa/chatgpt-next-web
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

resources: {}

tolerations: []

affinity: {}
