# Default values for chatgpt-next-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

chatgpt:
  {}
  # baseUrl: "https://api.openai.com"
  # apiKey: ""
  # password: ""
  # hideUserApiKey: '0'
  # disableGPT4: '1'

image:
  repository: yidadaa/chatgpt-next-web
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
    # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector:
  {}
  # kubernetes.io/hostname: xxx

tolerations: []

affinity: {}
